plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mozzi.ships'
    compileSdk 34

    defaultConfig {
        applicationId 'com.mozzi.ships'
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    applicationVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "MozziShips_v${variant.versionName}.apk"
        }
    }
}
